### PR TITLE
Add support for modular multi-release JARs, fixes #337

### LINKED ISSUE #337: helidon-maven-plugin:jlink-image does not support multi release modules with module-info not in root
Hello there, good helidon devs!

The 2.0.0-alpha1 release of SLF4J places the `module-info.class` inside `META-INF/versions/9`. It seems like the helidon-maven-plugin does not treat those jars as named modules and fails to build the runtime image.

To reproduce:
1. `git clone https://github.com/zimmi/helidon-multi-release-jlink-bug.git`
1. `mvn clean install`

Stacktrace (running `mvn clean install -e`):
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 4.19
[INFO] os.detected.version.major: 4
[INFO] os.detected.version.minor: 19
[INFO] os.detected.release: debian
[INFO] os.detected.release.version: 10
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64
[INFO] 
[INFO] --------< io.helidon.examples:helidon-multi-release-jlink-bug >---------
[INFO] Building helidon-multi-release-jlink-bug 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ helidon-multi-release-jlink-bug ---
[INFO] Deleting /home/thomas/gitstuff/helidon-multi-release-jlink-bug/target
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ helidon-multi-release-jlink-bug ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/thomas/gitstuff/helidon-multi-release-jlink-bug/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ helidon-multi-release-jlink-bug ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/thomas/gitstuff/helidon-multi-release-jlink-bug/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ helidon-multi-release-jlink-bug ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/thomas/gitstuff/helidon-multi-release-jlink-bug/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ helidon-multi-release-jlink-bug ---
[INFO] Changes detected - recompiling the module!
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ helidon-multi-release-jlink-bug ---
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.2:copy-dependencies (copy-libs) @ helidon-multi-release-jlink-bug ---
[INFO] Copying slf4j-api-2.0.0-alpha1.jar to /home/thomas/gitstuff/helidon-multi-release-jlink-bug/target/libs/slf4j-api-2.0.0-alpha1.jar
[INFO] Copying slf4j-jdk14-2.0.0-alpha1.jar to /home/thomas/gitstuff/helidon-multi-release-jlink-bug/target/libs/slf4j-jdk14-2.0.0-alpha1.jar
[INFO] 
[INFO] --- helidon-maven-plugin:2.1.2:report (third-party-license-report) @ helidon-multi-release-jlink-bug ---
[INFO] Scanning helidon-multi-release-jlink-bug
[INFO] Reading input from HELIDON_THIRD_PARTY_LICENSES.xml on classpath
[INFO] Writing output to /home/thomas/gitstuff/helidon-multi-release-jlink-bug/target/HELIDON_THIRD_PARTY_LICENSES.txt
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ helidon-multi-release-jlink-bug ---
[INFO] Building jar: /home/thomas/gitstuff/helidon-multi-release-jlink-bug/target/helidon-multi-release-jlink-bug.jar
[INFO] 
[INFO] --- helidon-maven-plugin:2.1.2:jlink-image (default) @ helidon-multi-release-jlink-bug ---
[INFO] 
[INFO] Creating Java Runtime Image helidon-multi-release-jlink-bug-jri from JDK 15.0.1+9-18 and helidon-multi-release-jlink-bug.jar, built with Helidon 0.0.0
[INFO] Collecting Java module dependencies
[INFO]   checking module io.helidon.examples.quickstart.se
[INFO]   checking slf4j-api-2.0.0-alpha1.jar
[INFO]   checking slf4j-jdk14-2.0.0-alpha1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.901 s
[INFO] Finished at: 2020-12-19T02:47:48+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.helidon.build-tools:helidon-maven-plugin:2.1.2:jlink-image (default) on project helidon-multi-release-jlink-bug: Image generation error: Module org.slf4j not found, required by org.slf4j.jul -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.helidon.build-tools:helidon-maven-plugin:2.1.2:jlink-image (default) on project helidon-multi-release-jlink-bug: Image generation error
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Image generation error
    at io.helidon.build.maven.link.JLinkImageMojo.execute (JLinkImageMojo.java:141)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.module.FindException: Module org.slf4j not found, required by org.slf4j.jul
    at java.lang.module.Resolver.findFail (Resolver.java:894)
    at java.lang.module.Resolver.resolve (Resolver.java:191)
    at java.lang.module.Resolver.resolve (Resolver.java:140)
    at java.lang.module.Configuration.resolve (Configuration.java:422)
    at java.lang.module.Configuration.resolve (Configuration.java:256)
    at com.sun.tools.jdeps.JdepsConfiguration$Builder.build (JdepsConfiguration.java:564)
    at com.sun.tools.jdeps.JdepsTask.buildConfig (JdepsTask.java:603)
    at com.sun.tools.jdeps.JdepsTask.run (JdepsTask.java:557)
    at com.sun.tools.jdeps.JdepsTask.run (JdepsTask.java:533)
    at com.sun.tools.jdeps.Main.run (Main.java:64)
    at com.sun.tools.jdeps.Main$JDepsToolProvider.run (Main.java:73)
    at java.util.spi.ToolProvider.run (ToolProvider.java:138)
    at io.helidon.linker.JavaDependencies.addJar (JavaDependencies.java:133)
    at io.helidon.linker.JavaDependencies.lambda$collect$1 (JavaDependencies.java:88)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1625)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining (Streams.java:735)
    at java.util.stream.ReferencePipeline$Head.forEach (ReferencePipeline.java:658)
    at io.helidon.linker.JavaDependencies.collect (JavaDependencies.java:84)
    at io.helidon.linker.JavaDependencies.collect (JavaDependencies.java:73)
    at io.helidon.linker.Application.javaDependencies (Application.java:78)
    at io.helidon.linker.Linker.collectJavaDependencies (Linker.java:158)
    at io.helidon.linker.Linker.link (Linker.java:118)
    at io.helidon.build.maven.link.JLinkImageMojo.execute (JLinkImageMojo.java:139)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

`helidon-maven-plugin`: 2.1.2

`java --version`
```
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```

Please let me know if you need further info.

### PR DESCRIPTION
**Pull request by zimmi**
I also added a tiny `multi-release.jar` file to test the fix for #337 .

### CODE REVIEW

**Comment by romain-grecourt** [comment]
It failing because `multi-release.jar` is not excluded from copyright duty.

Though, excluding copyright for this doesn't feel right. Can move this to the `integration-test` phase ?
I.e:
- add a project under `src/it/projects/multi-release`
- use `maven-invoker-plugin` to build the project during the phase `pre-integration-test`
- use failsafe to run a new test during the phase `integration-test`

Let me know if you need help for that.
I'll take a look and review the actual changes.

**Comment by zimmi** [comment]
Thanks for taking a look @romain-grecourt ! :)
I'll try to change the test when I'm off work.

**Comment by zimmi** [comment]
Rebased and removed the prebuilt `multi-release.jar` file, it's now generated on each build as suggested.

I already signed the OCA, seems like it's just not migrated over to the new system yet.

**Review by romain-grecourt — APPROVED** [review]

**Comment by zimmi** [comment]
Hey, thanks a lot for fixing this, much appreciated @romain-grecourt :+1:

**Pull request merged**
