### PR TITLE
Support for groupid and artifactid in init command

### PR DESCRIPTION
**Pull request by spericas**
Support for groupid and artifactid in init command

### CODE REVIEW

**Comment by romain-grecourt** [comment]
This change is fine, but we need to make sure we are on the same page regarding how support a proper batch mode for the init command.

We could do this in different ways:

1) Don't hard-code any template properties as cli options, instead pass them all as system properties, provide a way to describe templates in order to help users figure-out how to pass values.

2) Hard-code common "important" template properties as cli options, e.g. groupId, artifactId, version, package etc.. ; other template properties are passed as system properties using `-Dkey=value. This also means we need a way to describe templates in order to help users figure-out how to pass values.

3) Map template properties as cli options dynamically. We'd have the cli download some metadata about the template and map the template properties to cli options on the fly. This would have to be a 2 pass process since the template is identified with `--flavor` and `--helidon-version`

- Some other way ?

**Comment by spericas** [comment]
> This change is fine, but we need to make sure we are on the same page regarding how to support a proper batch mode for the init command.

Is there any other mode other than "batch" mode?

> 
> We could do this in different ways:
> 
> 1. Don't hard-code any template properties as cli options, instead pass them all as system properties, provide a way to describe templates in order to help users figure-out how to pass values.
> 2. Hard-code common "important" template properties as cli options, e.g. groupId, artifactId, version, package etc.. ; other template properties are passed as system properties using `-Dkey=value. This also means we need a way to describe templates in order to help users figure-out how to pass values.
> 3. Map template properties as cli options dynamically. We'd have the cli download some metadata about the template and map the template properties to cli options on the fly. This would have to be a 2 pass process since the template is identified with `--flavor` and `--helidon-version`
> 
> * Some other way ?

1) Too inconvenient
2) Seems just right
3) Don't see the need for the added complexity given the scope of the CLI

**Comment by romain-grecourt** [comment]
> Is there any mode other than "batch" mode?
The interactive mode.

> 1. Too inconvenient
> 2. Seems just right

Other than `groupId`, `artifactId`, `version`, I think `package` also deserves to be mapped as a cli option.

> 3. Don't see the need for the added complexity given the scope of the CLI

Indeed this option has more complexity, I'm not even sure it would be more functional than \#2. 

Again, I don't think we are on the same page regarding scope.

**Comment by spericas** [comment]
> > Is there any mode other than "batch" mode?
> 
> The interactive mode.

 Didn't think we would support that for init, but I guess it would make sense.

> 
> > 1. Too inconvenient
> > 2. Seems just right
> 
> Other than `groupId`, `artifactId`, `version`, I think `package` also deserves to be mapped as a cli option.
> 
> > 1. Don't see the need for the added complexity given the scope of the CLI
> 
> Indeed this option has more complexity, I'm not even sure it would be more functional than #2.
> 
> Again, I don't think we are on the same page regarding scope.

Very much so, I believe I'm in the minority on what the real scope of the CLI should be.

**Pull request merged**
